version: '3'
services:
  ursim:
    container_name: ursim
    image: universalrobots/ursim_e-series:latest
    restart: unless-stopped
    environment:
      - ROBOT_MODEL=UR10 #robot model
      - VERSION=5.11.1.108318
      - URSIM="https://s3-eu-west-1.amazonaws.com/ur-support-site/118926/URSim_Linux-5.11.1.108318.tar.gz"
    ports:
      - 5900:5900 #Connect with a VNC client
      - 6080:6080 #Connect into a browser to access to the interface without VNC
      - 30001-30004:30001-30004 #Real-time client interface
    extra_hosts:
      - "host.docker.internal:192.168.1.200"

    volumes:
      - ./docker_volumes/programs:/ursim/programs
      - ursim-gui-cache:/ursim/GUI
      - urcap-build-cache:/ursim/.urcaps

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./docker_volumes/mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883 #mqtt port
    stdin_open: true
    tty: true

volumes:
  ursim-gui-cache:
  urcap-build-cache:
