version: '3'
services:
  ursim:
    container_name: ursim
    image: universalrobots/ursim_e-series:latest
    restart: unless-stopped
    environment:
      - ROBOT_MODEL=UR5 #robot model
    ports:
      - 5900:5900 #Connect with a VNC client
      - 6080:6080 #Connect into a browser to access to the interface without VNC
      
    volumes:
      - docker_volumes/programs:/ursim/programs

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - docker_volumes/moquitto/config:/mosquitto/config
    ports:
      - 1883:1883 #mqtt port
    stdin_open: true 
    tty: true

      